### 1. Implementation using pure python

In [1]:
import numpy as np
import math

# Problem 1

In [2]:
w1, x1, w2, x2 = np.pi, 1, np.pi, 0.5

f = lambda A: 1/A
A = lambda B,C: B+C+2
B = lambda D: D**2
C = lambda F: np.cos(F)
D = lambda E: np.sin(E)
E = lambda w1, x1: w1*x1
F = lambda w2, x2: w2*x2

dfda = lambda A: -1/A**2
dadb = lambda B: 1
dadc = lambda C: 1
dbdd = lambda D: 2*D
dcdf = lambda F: -np.sin(F)
ddde = lambda E: np.cos(E)
dedx1 = lambda w1,x1: w1
dedw1 = lambda w1,x1: x1
dfdx2 = lambda w2,x2: w2
dfdw2 = lambda w2,x2: x2

print("f(w1, x1, w2, x2):\n", f(A(B(D(E(w1,x1))), C(F(w2,x2)))))
print("A(w1, x1, w2, x2):\n", A(B(D(E(w1,x1))), C(F(w2,x2))))
print("B(w1, x1, w2, x2):\n", B(D(E(w1,x1))))
print("C(w1, x1, w2, x2):\n", C(F(w2,x2)))
print("D(w1, x1, w2, x2):\n", D(E(w1,x1)))
print("E(w1, x1, w2, x2):\n", E(w1,x1))
print("F(w1, x1, w2, x2):\n",F(w2,x2))
print("w1:\n", w1)
print("x1:\n", x1)
print("w2:\n", w2)
print("x2:\n", x2)
print("df/dA:\n", dfda(A(B(D(E(w1,x1))), C(F(w2,x2)))))
print("df/dB:\n", dadb(B(D(E(w1,x1))))*dfda(A(B(D(E(w1,x1))), C(F(w2,x2)))))
print("df/dC:\n", dadc(C(F(w2,x2)))*dfda(A(B(D(E(w1,x1))), C(F(w2,x2)))))
print("df/dD:\n", dbdd(D(E(w1,x1)))*dadb(B(D(E(w1,x1))))*dfda(A(B(D(E(w1,x1))), C(F(w2,x2)))))
print("df/dE:\n", ddde(E(w1,x1))*dbdd(D(E(w1,x1)))*dadb(B(D(E(w1,x1))))*dfda(A(B(D(E(w1,x1))), C(F(w2,x2)))))
print("df/dF:\n", dcdf(F(w2,x2))*dadc(C(F(w2,x2)))*dfda(A(B(D(E(w1,x1))), C(F(w2,x2)))))
print("df/dw1:\n", dedw1(w1,x1)*ddde(E(w1,x1))*dbdd(D(E(w1,x1)))*dadb(B(D(E(w1,x1))))*dfda(A(B(D(E(w1,x1))), C(F(w2,x2)))))
print("df/dx1:\n", dedx1(w1,x1)*ddde(E(w1,x1))*dbdd(D(E(w1,x1)))*dadb(B(D(E(w1,x1))))*dfda(A(B(D(E(w1,x1))), C(F(w2,x2)))))
print("df/dw2:\n", dfdw2(w2,x2)*dcdf(F(w2,x2))*dadc(C(F(w2,x2)))*dfda(A(B(D(E(w1,x1))), C(F(w2,x2)))))
print("df/dx2:\n", dfdx2(w2,x2)*dcdf(F(w2,x2))*dadc(C(F(w2,x2)))*dfda(A(B(D(E(w1,x1))), C(F(w2,x2)))))


f(w1, x1, w2, x2):
 0.5
A(w1, x1, w2, x2):
 2.0
B(w1, x1, w2, x2):
 1.4997597826618576e-32
C(w1, x1, w2, x2):
 6.123233995736766e-17
D(w1, x1, w2, x2):
 1.2246467991473532e-16
E(w1, x1, w2, x2):
 3.141592653589793
F(w1, x1, w2, x2):
 1.5707963267948966
w1:
 3.141592653589793
x1:
 1
w2:
 3.141592653589793
x2:
 0.5
df/dA:
 -0.25
df/dB:
 -0.25
df/dC:
 -0.25
df/dD:
 -6.123233995736766e-17
df/dE:
 6.123233995736766e-17
df/dF:
 0.25
df/dw1:
 6.123233995736766e-17
df/dx1:
 1.9236706937217898e-16
df/dw2:
 0.125
df/dx2:
 0.7853981633974483


# Problem 2

In [19]:

sigmoid = lambda x: 1/(1+np.exp(-x))

f = lambda A: np.linalg.norm(A)**2

dfda = lambda A: 2*A
A = lambda B: sigmoid(B)

dadb = lambda B: np.multiply(sigmoid(B),(1 - sigmoid(B)))
B = lambda W,x: np.matmul(W,x)

dbdx = lambda W,x,B: W.transpose()
dbdw = lambda W,x,B: x.transpose()

x = np.matrix([[-1], [1], [-1]])
W = np.matrix([[0, 1, 2],[0, 0, 1],[1, 0, 0]])


print("f(W,x):\n", f(A(B(W,x))))
print("A(W,x):\n", A(B(W,x)))
print("B(W,x):\n", B(W,x))
print("W:\n", W)
print("x:\n", x)
print("df/dA:\n", dfda(A(B(W,x))))
print("df/dB:\n", np.multiply(dadb(B(W,x)),dfda(A(B(W,x)))))
print("df/dx:\n", np.matmul(dbdx(W,x,B(W,x)), np.multiply(dadb(B(W,x)),dfda(A(B(W,x))))))
print("df/dW:\n", np.matmul( np.multiply(dadb(B(W,x)),dfda(A(B(W,x)))), dbdw(W,x,B(W,x))))

f(W,x):
 0.21698846438553976
A(W,x):
 [[0.26894142]
 [0.26894142]
 [0.26894142]]
B(W,x):
 [[-1]
 [-1]
 [-1]]
W:
 [[0 1 2]
 [0 0 1]
 [1 0 0]]
x:
 [[-1]
 [ 1]
 [-1]]
df/dA:
 [[0.53788284]
 [0.53788284]
 [0.53788284]]
df/dB:
 [[0.10575419]
 [0.10575419]
 [0.10575419]]
df/dx:
 [[0.10575419]
 [0.10575419]
 [0.31726256]]
df/dW:
 [[-0.10575419  0.10575419 -0.10575419]
 [-0.10575419  0.10575419 -0.10575419]
 [-0.10575419  0.10575419 -0.10575419]]


#### 2. Implementation using pytorch

In [4]:
import torch
from torch import FloatTensor
from torch.autograd import Variable

# Problem 1

In [5]:
weights = [Variable(FloatTensor([i]), requires_grad=True) for i in (math.pi, math.pi, 1, 0.5)]

w1, w2, x1, x2 = weights

C = torch.cos(x2*w2)
B = torch.sin(x1*w1)
D = B**2
A = D + C
L = 1/(2+A)

L.backward()



weights = Variable(FloatTensor([[0,1,2],[0, 0, 1], [1, 0, 0]]), requires_grad=True)
xs =  Variable(FloatTensor([[-1], [1], [-1]]), requires_grad=True)

B = torch.mm(weights,xs)
A = torch.sigmoid(B)
L = torch.norm(A, 2)**2

L.backward()

print("Gradient of w1 at the chosen inputs: \n", w1.grad.data)
print("Gradient of x1 at the chosen inputs: \n", x1.grad.data)
print("Gradient of w2 at the chosen inputs: \n", w2.grad.data)
print("Gradient of x2 at the chosen inputs: \n", x2.grad.data)



Gradient of w1 at the chosen inputs: 
 tensor([-4.3711e-08])
Gradient of x1 at the chosen inputs: 
 tensor([-1.3732e-07])
Gradient of w2 at the chosen inputs: 
 tensor([0.1250])
Gradient of x2 at the chosen inputs: 
 tensor([0.7854])


# Problem 2

In [7]:
weights = Variable(FloatTensor([[0,1,2],[0, 0, 1], [1, 0, 0]]), requires_grad=True)
xs =  Variable(FloatTensor([[-1], [1], [-1]]), requires_grad=True)

B = torch.mm(weights,xs)
A = torch.sigmoid(B)
L = torch.norm(A, 2)**2

L.backward()

print("Gradient of W at the chosen inputs: \n", weights.grad.data)
print("Gradient of x at the chosen inputs: \n", xs.grad.data)


Gradient of W at the chosen inputs: 
 tensor([[-0.1058,  0.1058, -0.1058],
        [-0.1058,  0.1058, -0.1058],
        [-0.1058,  0.1058, -0.1058]])
Gradient of x at the chosen inputs: 
 tensor([[0.1058],
        [0.1058],
        [0.3173]])
